export const PREVIEW_SOURCE_BY_DATASET_ID: Record<string, { table: string; sortCol: string }> = {
  'github.push-events.v1': { table: 'dl_push_events', sortCol: 'ts_kst' },
  'github.pull-request-events.v1': { table: 'dl_pull_request_events', sortCol: 'ts_kst' },
  'github.issues-events.v1': { table: 'dl_issues_events', sortCol: 'ts_kst' },
  'github.issue-comment-events.v1': { table: 'dl_issue_comment_events', sortCol: 'ts_kst' },
  'github.watch-events.v1': { table: 'dl_watch_events', sortCol: 'ts_kst' },
  'github.fork-events.v1': { table: 'dl_fork_events', sortCol: 'ts_kst' },
  'github.create-events.v1': { table: 'dl_create_events', sortCol: 'ts_kst' },
  'github.delete-events.v1': { table: 'dl_delete_events', sortCol: 'ts_kst' },
  'github.pull-request-review-events.v1': {
    table: 'dl_pull_request_review_events',
    sortCol: 'ts_kst',
  },
  'github.pull-request-review-comment-events.v1': {
    table: 'dl_pull_request_review_comment_events',
    sortCol: 'ts_kst',
  },
  'github.member-events.v1': { table: 'dl_member_events', sortCol: 'ts_kst' },
  'github.gollum-events.v1': { table: 'dl_gollum_events', sortCol: 'ts_kst' },
  'github.release-events.v1': { table: 'dl_release_events', sortCol: 'ts_kst' },
  'github.public-events.v1': { table: 'dl_public_events', sortCol: 'ts_kst' },
  'discord.messages.v1': {
    table: 'discord_messages',
    sortCol: 'created_at',
  },
  // pseudolab (79 tables)
  'pseudolab.action-items.v1': { table: 'dl_action_items', sortCol: 'base_date' },
  'pseudolab.admin-calendar-events.v1': { table: 'dl_admin_calendar_events', sortCol: 'base_date' },
  'pseudolab.artifact-logs.v1': { table: 'dl_artifact_logs', sortCol: 'base_date' },
  'pseudolab.badges.v1': { table: 'dl_badges', sortCol: 'base_date' },
  'pseudolab.blogs.v1': { table: 'dl_blogs', sortCol: 'base_date' },
  'pseudolab.bug-assignees.v1': { table: 'dl_bug_assignees', sortCol: 'base_date' },
  'pseudolab.bug-comments.v1': { table: 'dl_bug_comments', sortCol: 'base_date' },
  'pseudolab.bug-events.v1': { table: 'dl_bug_events', sortCol: 'base_date' },
  'pseudolab.bug-reports.v1': { table: 'dl_bug_reports', sortCol: 'base_date' },
  'pseudolab.builder-onboarding.v1': { table: 'dl_builder_onboarding', sortCol: 'base_date' },
  'pseudolab.community-feed.v1': { table: 'dl_community_feed', sortCol: 'base_date' },
  'pseudolab.dormitory-messages.v1': { table: 'dl_dormitory_messages', sortCol: 'base_date' },
  'pseudolab.email-verification-codes.v1': {
    table: 'dl_email_verification_codes',
    sortCol: 'base_date',
  },
  'pseudolab.event-cards.v1': { table: 'dl_event_cards', sortCol: 'base_date' },
  'pseudolab.event-committee.v1': { table: 'dl_event_committee', sortCol: 'base_date' },
  'pseudolab.event-missions.v1': { table: 'dl_event_missions', sortCol: 'base_date' },
  'pseudolab.event-participants.v1': { table: 'dl_event_participants', sortCol: 'base_date' },
  'pseudolab.event-registrations.v1': { table: 'dl_event_registrations', sortCol: 'base_date' },
  'pseudolab.event-sessions.v1': { table: 'dl_event_sessions', sortCol: 'base_date' },
  'pseudolab.event-speaker-submissions.v1': {
    table: 'dl_event_speaker_submissions',
    sortCol: 'base_date',
  },
  'pseudolab.event-sponsor-submissions.v1': {
    table: 'dl_event_sponsor_submissions',
    sortCol: 'base_date',
  },
  'pseudolab.event-sponsors.v1': { table: 'dl_event_sponsors', sortCol: 'base_date' },
  'pseudolab.event-staff.v1': { table: 'dl_event_staff', sortCol: 'base_date' },
  'pseudolab.event-timeline.v1': { table: 'dl_event_timeline', sortCol: 'base_date' },
  'pseudolab.events.v1': { table: 'dl_events', sortCol: 'base_date' },
  'pseudolab.feed-comments.v1': { table: 'dl_feed_comments', sortCol: 'base_date' },
  'pseudolab.follows.v1': { table: 'dl_follows', sortCol: 'base_date' },
  'pseudolab.highlight-comments.v1': { table: 'dl_highlight_comments', sortCol: 'base_date' },
  'pseudolab.highlight-likes.v1': { table: 'dl_highlight_likes', sortCol: 'base_date' },
  'pseudolab.highlights.v1': { table: 'dl_highlights', sortCol: 'base_date' },
  'pseudolab.legacy-members.v1': { table: 'dl_legacy_members', sortCol: 'base_date' },
  'pseudolab.magic-maps.v1': { table: 'dl_magic_maps', sortCol: 'base_date' },
  'pseudolab.magic-progress.v1': { table: 'dl_magic_progress', sortCol: 'base_date' },
  'pseudolab.notifications.v1': { table: 'dl_notifications', sortCol: 'base_date' },
  'pseudolab.opportunities.v1': { table: 'dl_opportunities', sortCol: 'base_date' },
  'pseudolab.opportunity-beneficiaries.v1': {
    table: 'dl_opportunity_beneficiaries',
    sortCol: 'base_date',
  },
  'pseudolab.opportunity-likes.v1': { table: 'dl_opportunity_likes', sortCol: 'base_date' },
  'pseudolab.page-views.v1': { table: 'dl_page_views', sortCol: 'base_date' },
  'pseudolab.profile-careers.v1': { table: 'dl_profile_careers', sortCol: 'base_date' },
  'pseudolab.profiles.v1': { table: 'dl_profiles', sortCol: 'base_date' },
  'pseudolab.program-feedbacks.v1': { table: 'dl_program_feedbacks', sortCol: 'base_date' },
  'pseudolab.program-followups.v1': { table: 'dl_program_followups', sortCol: 'base_date' },
  'pseudolab.program-likes.v1': { table: 'dl_program_likes', sortCol: 'base_date' },
  'pseudolab.project-application-history.v1': {
    table: 'dl_project_application_history',
    sortCol: 'base_date',
  },
  'pseudolab.project-applications.v1': { table: 'dl_project_applications', sortCol: 'base_date' },
  'pseudolab.project-attendance.v1': { table: 'dl_project_attendance', sortCol: 'base_date' },
  'pseudolab.project-docs.v1': { table: 'dl_project_docs', sortCol: 'base_date' },
  'pseudolab.project-members.v1': { table: 'dl_project_members', sortCol: 'base_date' },
  'pseudolab.project-sessions.v1': { table: 'dl_project_sessions', sortCol: 'base_date' },
  'pseudolab.project-tasks.v1': { table: 'dl_project_tasks', sortCol: 'base_date' },
  'pseudolab.projects.v1': { table: 'dl_projects', sortCol: 'base_date' },
  'pseudolab.quest-definitions.v1': { table: 'dl_quest_definitions', sortCol: 'base_date' },
  'pseudolab.random-squad-queue.v1': { table: 'dl_random_squad_queue', sortCol: 'base_date' },
  'pseudolab.recruit-applications.v1': { table: 'dl_recruit_applications', sortCol: 'base_date' },
  'pseudolab.registration-submissions.v1': {
    table: 'dl_registration_submissions',
    sortCol: 'base_date',
  },
  'pseudolab.resource-comments.v1': { table: 'dl_resource_comments', sortCol: 'base_date' },
  'pseudolab.resource-reactions.v1': { table: 'dl_resource_reactions', sortCol: 'base_date' },
  'pseudolab.secret-comments.v1': { table: 'dl_secret_comments', sortCol: 'base_date' },
  'pseudolab.secret-interactions.v1': { table: 'dl_secret_interactions', sortCol: 'base_date' },
  'pseudolab.secret-posts.v1': { table: 'dl_secret_posts', sortCol: 'base_date' },
  'pseudolab.secret-profiles.v1': { table: 'dl_secret_profiles', sortCol: 'base_date' },
  'pseudolab.session-submissions.v1': { table: 'dl_session_submissions', sortCol: 'base_date' },
  'pseudolab.speaker-submissions.v1': { table: 'dl_speaker_submissions', sortCol: 'base_date' },
  'pseudolab.sponsor-submissions.v1': { table: 'dl_sponsor_submissions', sortCol: 'base_date' },
  'pseudolab.sponsorship-requests.v1': { table: 'dl_sponsorship_requests', sortCol: 'base_date' },
  'pseudolab.squad-applications.v1': { table: 'dl_squad_applications', sortCol: 'base_date' },
  'pseudolab.squads.v1': { table: 'dl_squads', sortCol: 'base_date' },
  'pseudolab.user-badges.v1': { table: 'dl_user_badges', sortCol: 'base_date' },
  'pseudolab.user-follows.v1': { table: 'dl_user_follows', sortCol: 'base_date' },
  'pseudolab.user-influences.v1': { table: 'dl_user_influences', sortCol: 'base_date' },
  'pseudolab.user-missions.v1': { table: 'dl_user_missions', sortCol: 'base_date' },
  'pseudolab.user-quests.v1': { table: 'dl_user_quests', sortCol: 'base_date' },
  'pseudolab.user-roles.v1': { table: 'dl_user_roles', sortCol: 'base_date' },
  'pseudolab.user-which-projects.v1': { table: 'dl_user_which_projects', sortCol: 'base_date' },
  'pseudolab.wiki-articles.v1': { table: 'dl_wiki_articles', sortCol: 'base_date' },
  'pseudolab.wiki-categories.v1': { table: 'dl_wiki_categories', sortCol: 'base_date' },
  'pseudolab.wiki-pages.v1': { table: 'dl_wiki_pages', sortCol: 'base_date' },
  'pseudolab.wiki-revisions.v1': { table: 'dl_wiki_revisions', sortCol: 'base_date' },
  'pseudolab.xp-history.v1': { table: 'dl_xp_history', sortCol: 'base_date' },
}

export function hasPreviewSource(datasetId: string): boolean {
  return Object.prototype.hasOwnProperty.call(PREVIEW_SOURCE_BY_DATASET_ID, datasetId)
}
